// use library source from disk
@Library('automagic@release')_

// use library source from git
//@Library('automagic-git@release')_

pipeline {
	agent any
	stages {
		stage("AutoMagic") {
			steps {
				script {
					// use this job as template to develop pipelines for real projects
					println(am_greet("el disco duro"))
				}
			}
		}
	}
}